services:
    user_repository:
        class: AppBundle\Model\UserRepository
    stats_system:
        class: AppBundle\Service\StatsSystem
    marketing_system:
        class: AppBundle\Service\MarketingSystem

    user_service:
        class: AppBundle\Service\UserService
        arguments: [ @user_repository, @event_dispatcher ]

    email_change.listener:
        class: AppBundle\Event\EmailChangeListener
        arguments: [ @stats_system, @marketing_system, @monolog.logger.email_change ]
        tags:
            - { name: kernel.event_listener, event: EMAIL_CHANGE_EVENT, method: onEmailChange }

    email_change.command:
            class: AppBundle\Console\EmailChangeCommand
            arguments: [ @user_service ]
            tags:
                -  { name: console.command }